[investigation]
homePath   = $SPLUNK_DB/investigation/db
coldPath   = $SPLUNK_DB/investigation/colddb
thawedPath = $SPLUNK_DB/investigation/thaweddb
maxTotalDataSizeMB = 512000
frozenTimePeriodInSecs = 4294967295
