[monitor:///lab/logs/cloudtrail]
index = investigation
sourcetype = aws:cloudtrail
source = aws:cloudtrail
host = sim-cloudtrail
whitelist = \.json\.gz$
disabled = false

[monitor:///lab/logs/k8s_audit]
index = investigation
sourcetype = aws:eks:audit
source = aws:eks:audit
host = sim-eks-apiserver
whitelist = \.json\.gz$
disabled = false

[monitor:///lab/logs/edr]
index = investigation
sourcetype = crowdstrike:falcon:edr
source = crowdstrike:falcon:edr
host = sim-edr-sensor
whitelist = \.json\.gz$
disabled = false

[monitor:///lab/logs/github_audit]
index = investigation
sourcetype = github:cloud:audit
source = github:cloud:audit
host = sim-github-audit
whitelist = \.json\.gz$
disabled = false
