[aws:cloudtrail]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
TRUNCATE = 0
MAX_DAYS_AGO = 10951
TZ = UTC
TIME_PREFIX = "eventTime"\s*:\s*"
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ
MAX_TIMESTAMP_LOOKAHEAD = 2000

[aws:eks:audit]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
TRUNCATE = 0
MAX_DAYS_AGO = 10951
TZ = UTC
TIME_PREFIX = "requestReceivedTimestamp"\s*:\s*"
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%6NZ
MAX_TIMESTAMP_LOOKAHEAD = 2000

[crowdstrike:falcon:edr]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
TRUNCATE = 0
MAX_DAYS_AGO = 10951
TZ = UTC
TIME_PREFIX = "timestamp"\s*:\s*"
TIME_FORMAT = %s%3N
MAX_TIMESTAMP_LOOKAHEAD = 4000

[github:cloud:audit]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
TRUNCATE = 0
MAX_DAYS_AGO = 10951
TZ = UTC
TIME_PREFIX = "@timestamp"\s*:\s*
TIME_FORMAT = %s%3N
MAX_TIMESTAMP_LOOKAHEAD = 128
